### ISSUE TITLE
App crashes when you select Register with explorer on Easy photomap

### ISSUE THREAD

**Issue by idimummy** [hanjoongcho/aaf-easyphotomap#1]
#### Expected behavior
Users should be able to select register with explorer to register new photo.

#### Actual behavior
Application crashes when you select register with explorer.

#### How to reproduce
Download Easy Photomap v1.1.56 v1.1.56 from play store [here](https://play.google.com/store/apps/details?id=me.blog.korn123.easyphotomap), launch it, select Register with explorer

* Operating system: Android Version 7.0  
* Device used: Tecno Boom J8

#### Recording Of The Bug
https://youtu.be/pcWi-om5ky0
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@kennykajo/bug-report-on-easy-photomap">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by hanjoongcho** [comment]
Some errors have been fixed in version 1.1.58.
Will the same issue occur in the latest version?
